name: Update Daily Image

on:
  schedule:
    - cron: '0 19 * * *'  # Runs every day at 19 UTC
  workflow_dispatch:
    inputs:
      manual_trigger:
        description: 'Manually trigger the workflow'
        default: 'true'

jobs:
  update-readme:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Git
        run: |
          git config --global user.email "action@github.com"
          git config --global user.name "GitHub Action"

      - name: Get current image
        id: get-current-image
        run: |
          current_image=$(grep -oP '(?<=src=").*?(?=")' README.md)
          echo "current_image=${current_image}" >> $GITHUB_ENV

      - name: Select random image
        id: select-random-image
        run: |
          images=(./images/*.jpg)
          num_images=${#images[@]}
          current_image=${{ env.current_image }}
          
          selected_image=${images[0]}  # Default to the first image in case of an infinite loop
          if [ $num_images -gt 1 ]; then
            while : ; do
              random_index=$(( RANDOM % num_images ))
              selected_image=${images[$random_index]}
              if [ "$selected_image" != "$current_image" ]; then
                break
              fi
            done
          fi
          
          echo "selected_image=${selected_image}" >> $GITHUB_ENV

      - name: Update README
        run: |
          sed -i '0,/src="[^"]*"/{s|src="[^"]*"|src="${{ env.selected_image }}"|}' README.md

      - name: Commit changes
        run: |
          git add README.md
          git commit -m "Update daily image"
          git push origin HEAD:main
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
