name: Update Daily Image

on:
  schedule:
    - cron: '0 19 * * *'  # Runs every day at 19:00 UTC
  workflow_dispatch:  # Enable manual triggering
    inputs:
      manual_trigger:
        description: 'Manually trigger the workflow'
        default: 'true'

jobs:
  update-readme:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Select random image
        id: select-random-image
        run: |
          images=(./images/*.jpg)
          num_images=${#images[@]}
          random_index=$(( RANDOM % num_images ))
          selected_image=${images[$random_index]}
          echo "::set-output name=image_path::${selected_image}"

      - name: Update README
        run: |
          sed -i 's|src="[^"]*"|src="${{ steps.select-random-image.outputs.image_path }}"|g' README.md

      - name: Commit changes
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add README.md
          git commit -m "Update daily image"
          git push
