name: Update Daily Image

on:
  schedule:
    - cron: '0 18 * * *'  # Runs every day at 18:00 UTC

jobs:
  update-readme:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Select random image
        id: select_random_image
        run: |
          images=(./images/*.jpg ./images/*.png ./images/*.jpeg)
          num_images=${#images[@]}
          random_index=$(( RANDOM % num_images ))
          selected_image=${images[$random_index]}
          echo "selected_image=$selected_image" >> $GITHUB_ENV

      - name: Update README
        run: |
          sed -i "s|<img alt=\"Daily Image\" src=\".*\" />|<img alt=\"Daily Image\" src=\"${selected_image}\" />|" README.md

      - name: Commit changes
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add README.md
          git commit -m "Update daily image"
          git push
